### PR TITLE
Populate the fast store on partial read

### LINKED ISSUE #270: Protos not kept in fast store
If `ac_utils` is used to `get_and_decode_digest` then the length parameter is passed to `get_part` which causes it to skip out of the local pinning in the fast store because length is set (`MAX_ACTION_MSG_SIZE`).

### PR DESCRIPTION
**Pull request by chrisstaite-menlo**
Resolves #270

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/272)

### CODE REVIEW

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/272)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @chrisstaite-menlo)

*[a discussion](https://reviewable.io/reviews/allada/turbo-cache/272#-Ne4aNDe11q9RyFqRI3m:-Ne4aNDe11q9RyFqRI3n:b9ezbs0) (no related file):*
I started reviewing this then I thought... this is a common issue and should probably be simplified and tested.

I created an example here, how I'd suggest doing it:
https://github.com/allada/turbo-cache/commit/fb9b4be145bcfbc8c29478380a7427092399fc7f

___
___
*[`cas/store/fast_slow_store.rs` line 246 at r1](https://reviewable.io/reviews/allada/turbo-cache/272#-Ne3ttrdE1rJFc_aeavg:-Ne3ttrdE1rJFc_aeavh:b-qk6hvh) ([raw file](https://github.com/allada/turbo-cache/blob/32760c7e03c4a490b802a59431e7358e8a03e202/cas/store/fast_slow_store.rs#L246)):*
> ```XML
>                     writer_pin.send(output_slice).boxed()
>                 };
>                 let (fast_tx_res, writer_res) = join!(fast_tx.send(output_buf).boxed(), writer_fut,);
> ```

nit: Trailing comma.
___
*[`cas/store/tests/fast_slow_store_test.rs` line 119 at r1](https://reviewable.io/reviews/allada/turbo-cache/272#-Ne3t0vPC8PzihgAcEkJ:-Ne3t0vPC8PzihgAcEkK:b-i2src2) ([raw file](https://github.com/allada/turbo-cache/blob/32760c7e03c4a490b802a59431e7358e8a03e202/cas/store/tests/fast_slow_store_test.rs#L119)):*
> ```XML
> 
>     #[tokio::test]
>     async fn partial_reads_copy_full_to_slow_store_test() -> Result<(), Error> {
> ```

nit: I think this is named wrong I think it should be: `partial_reads_copy_full_to_fast_store_test`
___
*[`cas/worker/running_actions_manager.rs` line 884 at r1](https://reviewable.io/reviews/allada/turbo-cache/272#-Ne3rnynAcEzVz-1iwym:-Ne3rnyo0_4LKUWe2F5M:bd706gz) ([raw file](https://github.com/allada/turbo-cache/blob/32760c7e03c4a490b802a59431e7358e8a03e202/cas/worker/running_actions_manager.rs#L884)):*
> ```XML
>         if execution_result.exit_code != 0 {
>             log::info!(
>                 "Command exited unsuccessfully: {} {}",
> ```

Can we change this to something like this?

`Command returned exit code {}: {} {}`

`unsuccessfully` would not be a common thing for people to search logs for.

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/272)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @allada)

*[a discussion](https://reviewable.io/reviews/allada/turbo-cache/272#-Ne4aNDe11q9RyFqRI3m:-Ne7v9Za3n6uG9Z-n4C_:bxymkii) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I started reviewing this then I thought... this is a common issue and should probably be simplified and tested.

I created an example here, how I'd suggest doing it:
https://github.com/allada/turbo-cache/commit/fb9b4be145bcfbc8c29478380a7427092399fc7f
</blockquote></details>

I modified the logic a little because I found it much easier to reason with calculating the start and end then checking to see if they were in the range.

___
___
*[`cas/worker/running_actions_manager.rs` line 884 at r1](https://reviewable.io/reviews/allada/turbo-cache/272#-Ne3rnynAcEzVz-1iwym:-Ne7lThC9r22-_04vEGu:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/32760c7e03c4a490b802a59431e7358e8a03e202/cas/worker/running_actions_manager.rs#L884)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Can we change this to something like this?

`Command returned exit code {}: {} {}`

`unsuccessfully` would not be a common thing for people to search logs for.
</blockquote></details>

Done.

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/272#-:-Ne9Nxni2jvY_ucZsuRY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)

**Review by chrisstaite-menlo — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/272)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)

**Pull request merged**
