### PR TITLE
Revert "Update all dependencies to their latest versions"

### PR DESCRIPTION
**Pull request by allada**
This reverts commit 6a7284138c8835ce4abdb61bee3a7d2eb33a7290.

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/148)

### CODE REVIEW

**Comment by allada** [comment]
revert for: #146

**Comment by allada** [comment]
cc: @aaronmondal

**Comment by aaronmondal** [comment]
Sure let's revert this to unblock @chrisstaite-menlo first. We can re-revert when #148 is resolved.

**Review by aaronmondal — APPROVED** [review]

**Comment by chrisstaite** [comment]
This isn't necessary, #147 fixes it

**Pull request closed without merging**
