### PR TITLE
Use Axum's router which supports multiple service types

### PR DESCRIPTION
**Pull request by allada**
This is in prepopration to add prometheus endpoints. It'll allow us to use the same http port that tonic uses, but we can route different url requests to different services with axum.

toward: #193

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/194)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/194)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @chrisstaite-menlo)

*[a discussion](https://reviewable.io/reviews/allada/turbo-cache/194#-N_VQrmF28ZfiOd5PwbW:-N_VQrmF28ZfiOd5PwbX:b-bih0v6) (no related file):*
+@chrisstaite-menlo

I tested in my local setting, but if you have a simple way to make sure this does not break any of you, i'd be awesome!

___

**Review by chrisstaite-menlo — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/194)* status: all files reviewed, 1 unresolved discussion (waiting on @allada)

*[a discussion](https://reviewable.io/reviews/allada/turbo-cache/194#-N_VQrmF28ZfiOd5PwbW:-N_XlF4v3JFUgolu2aA9:b-6e0eny) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

+@chrisstaite-menlo

I tested in my local setting, but if you have a simple way to make sure this does not break any of you, i'd be awesome!
</blockquote></details>

Just doing final testing on my wait_execution branch and I'll then bring that in and test this change too.

___

**Comment by chrisstaite-menlo** [comment]
Just tried this out, doesn't appear to cause any issues for Goma.

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Pull request merged**
