### PR TITLE
Jobs now honor timeout in action

### PR DESCRIPTION
**Pull request by allada**
fixes: #211

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/223)

### CODE REVIEW

**Review by chrisstaite-menlo — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/223)* status: all files reviewed, 1 unresolved discussion (waiting on @allada)

___
*[`cas/worker/running_actions_manager.rs` line 588 at r1](https://reviewable.io/reviews/allada/turbo-cache/223#-NaBYeLk95RBa0Iwvl8A:-NaBYeLk95RBa0Iwvl8B:b1pm4k3) ([raw file](https://github.com/allada/turbo-cache/blob/91d1c033f5f1cf611647550293ef5a3fd56c9587/cas/worker/running_actions_manager.rs#L588)):*
> ```XML
>                         log::error!("Could not kill process in RunningActionsManager for timeout : {:?}", e);
>                     }
>                     child_process.wait().await.err_tip(|| "Failed to collect exit code of process after timeout")?;
> ```

If the process was hanging, then the stdout and stderr are probably useful for debugging purposes and we simply discard them here.
___
*[`cas/worker/running_actions_manager.rs` line 933 at r1](https://reviewable.io/reviews/allada/turbo-cache/223#-NaBYubX8r39dEqjhfkJ:-NaBYubX8r39dEqjhfkK:b-bv1k13) ([raw file](https://github.com/allada/turbo-cache/blob/91d1c033f5f1cf611647550293ef5a3fd56c9587/cas/worker/running_actions_manager.rs#L933)):*
> ```XML
>         upload_strategy: UploadCacheResultsStrategy,
>         max_action_timeout: Duration,
>         now_fn: NowFn,
> ```

Could combine the `NowFn` and `SleepFn` into a debugging struct that has a default implementation.  That should get rid of the clippy issue and allow for future additions of debugging functions.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/223)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisstaite-menlo)

___
*[`cas/worker/running_actions_manager.rs` line 588 at r1](https://reviewable.io/reviews/allada/turbo-cache/223#-NaBYeLk95RBa0Iwvl8A:-NaHkDYe1SqAwoYuvoyu:bempy4k) ([raw file](https://github.com/allada/turbo-cache/blob/91d1c033f5f1cf611647550293ef5a3fd56c9587/cas/worker/running_actions_manager.rs#L588)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

If the process was hanging, then the stdout and stderr are probably useful for debugging purposes and we simply discard them here.
</blockquote></details>

Oh man the rabbit hole I just came out of, see #225 .

Done.
___
*[`cas/worker/running_actions_manager.rs` line 933 at r1](https://reviewable.io/reviews/allada/turbo-cache/223#-NaBYubX8r39dEqjhfkJ:-NaCp1bR1ZMUAwuIVidX:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/91d1c033f5f1cf611647550293ef5a3fd56c9587/cas/worker/running_actions_manager.rs#L933)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Could combine the `NowFn` and `SleepFn` into a debugging struct that has a default implementation.  That should get rid of the clippy issue and allow for future additions of debugging functions.
</blockquote></details>

Done.

**Review by chrisstaite-menlo — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/223)* status: all files reviewed, 2 unresolved discussions (waiting on @allada)

___
*[`cas/worker/running_actions_manager.rs` line 588 at r1](https://reviewable.io/reviews/allada/turbo-cache/223#-NaBYeLk95RBa0Iwvl8A:-NaHkv1159T0CHtvTC2D:b-ue409r) ([raw file](https://github.com/allada/turbo-cache/blob/91d1c033f5f1cf611647550293ef5a3fd56c9587/cas/worker/running_actions_manager.rs#L588)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Oh man the rabbit hole I just came out of, see #225 .

Done.
</blockquote></details>

Oh, wow...
___
*[`cas/worker/running_actions_manager.rs` line 607 at r2](https://reviewable.io/reviews/allada/turbo-cache/223#-NaHlKZU-ZhkmNGE_QmK:-NaHlKZU-ZhkmNGE_QmL:b3b2yny) ([raw file](https://github.com/allada/turbo-cache/blob/74efacec90d3478329b75ae9b40c1aec514d1014/cas/worker/running_actions_manager.rs#L607)):*
> ```XML
>                         log::error!("Could not kill process in RunningActionsManager for timeout : {:?}", e);
>                     }
>                     {
> ```

What's this scope for, we're already in one?
___
*[`cas/worker/running_actions_manager.rs` line 665 at r2](https://reviewable.io/reviews/allada/turbo-cache/223#-NaHlVLEBUU2kg6dfhDp:-NaHlVLEBUU2kg6dfhDq:bmvy7ux) ([raw file](https://github.com/allada/turbo-cache/blob/74efacec90d3478329b75ae9b40c1aec514d1014/cas/worker/running_actions_manager.rs#L665)):*
> ```XML
>                         log::error!("Could not get child process id, maybe already dead?");
>                     }
>                     {
> ```

This scope doesn't appear to be necessary either?6

**Review by chrisstaite-menlo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/223)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Review by chrisstaite-menlo — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/223)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @allada)

**Pull request merged**
