### PR TITLE
Support injecting property values into entry point command.

### LINKED ISSUE #261: Make platform properties available to entry point cmd
There are cases (Chromium build for example) where the entry point command needs to get information from the platform properties.  Injecting these into the environment would not be ideal as it might make conflicts, but injecting them into placeholders in the entry point command would allow this information to be passed in in a configurable way and allow such actions as running within a property specified container image.

### PR DESCRIPTION
**Pull request by chrisstaite-menlo**
Resolves #261

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/262)

### CODE REVIEW

**Comment by chrisstaite** [comment]
I'm thinking of making this a breaking change so entrypoint_cmd is a list

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/262)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @chrisstaite-menlo)

*[a discussion](https://reviewable.io/reviews/allada/turbo-cache/262#-NduRtJ20l1nWhDrRVtw:-NduRtJ3-KOHSe6-B_3d:b-z9xp27) (no related file):*
I think we should do this by injecting them in as environmental variables.

To prevent it from being a conflict, lets have the user specify the environmental variable they'd like to assign the properties too in the config.

I'm leaning towards a map, where the user specifies each environ what platform property to assign to it, as it would make it much easier to use.

___
___
*[`cas/worker/running_actions_manager.rs` line 559 at r1](https://reviewable.io/reviews/allada/turbo-cache/262#-NduQjKy3aDNOIHDcLcz:-NduQjKy3aDNOIHDcLd-:bimrcxo) ([raw file](https://github.com/allada/turbo-cache/blob/abb8cb75a393a452ad9ccb771883e9d9380ad7b3/cas/worker/running_actions_manager.rs#L559)):*
> ```XML
> 
>     fn inject_property<'a>(&'a self, argument: &'a str) -> &'a str {
>         if argument.starts_with('{') && argument.ends_with('}') {
> ```

nit: I'd rewrite this:
```rs
if !argument.starts_with('{') || !argument.ends_with('}') {
  return argument;
}
let property_name = &argument[1..argument.len() - 1];
match self.action_info.platform_properties.properties.get(property_name) {
  Some(PlatformPropertyValue::Exact(value)) => value.as_str(),
  // TODO: Support injecting minimum.
  Some(PlatformPropertyValue::Minimum(_)) => argument,
  Some(PlatformPropertyValue::Priority(value)) => value.as_str(),
  Some(PlatformPropertyValue::Unknown(value)) => value.as_str(),
  None => argument,
}
```
___
*[`cas/worker/running_actions_manager.rs` line 560 at r1](https://reviewable.io/reviews/allada/turbo-cache/262#-NduQeiVAuZpJgmGZAoe:-NduQeiW0GZIiTP-jkRC:b-qt19ay) ([raw file](https://github.com/allada/turbo-cache/blob/abb8cb75a393a452ad9ccb771883e9d9380ad7b3/cas/worker/running_actions_manager.rs#L560)):*
> ```XML
>     fn inject_property<'a>(&'a self, argument: &'a str) -> &'a str {
>         if argument.starts_with('{') && argument.ends_with('}') {
>             // Inject property
> ```

nit: needless comment.

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/262)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @allada)

*[a discussion](https://reviewable.io/reviews/allada/turbo-cache/262#-NduRtJ20l1nWhDrRVtw:-Ne2EycDBT14SwnLRFeW:b-896fix) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I think we should do this by injecting them in as environmental variables.

To prevent it from being a conflict, lets have the user specify the environmental variable they'd like to assign the properties too in the config.

I'm leaning towards a map, where the user specifies each environ what platform property to assign to it, as it would make it much easier to use.
</blockquote></details>

Done.

___

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/262)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @chrisstaite-menlo)

___
*[`config/cas_server.rs` line 325 at r2](https://reviewable.io/reviews/allada/turbo-cache/262#-Ne4d7nq5p3oIJbS5nzJ:-Ne4d7nq5p3oIJbS5nzK:b-1ymexs) ([raw file](https://github.com/allada/turbo-cache/blob/b365a3292151ee530cb170ec984ed37cdecf0602/config/cas_server.rs#L325)):*
> ```XML
>     /// the job with the value of the environment variable being the value of
>     /// the property of the action being executed of that name.
>     pub property_environments: Option<HashMap<String, String>>,
> ```

I think this logic is nearly identical to also supporting: https://github.com/allada/turbo-cache/issues/237

Can we do a few minor tweaks to this so we can pass in raw (static) values as well as dynamic values like platform properties?

Introducing a new enum is probably best and have the key be the source type of the string (ie: `Raw(String)` or `PlatformPropertyValue(String)`). This might be useful for other weird use cases in the future for metadata injection.

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/262)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @allada)

___
*[`config/cas_server.rs` line 325 at r2](https://reviewable.io/reviews/allada/turbo-cache/262#-Ne4d7nq5p3oIJbS5nzJ:-Ne7k6wzE5yGu8Hijofb:botlmy3) ([raw file](https://github.com/allada/turbo-cache/blob/b365a3292151ee530cb170ec984ed37cdecf0602/config/cas_server.rs#L325)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I think this logic is nearly identical to also supporting: https://github.com/allada/turbo-cache/issues/237

Can we do a few minor tweaks to this so we can pass in raw (static) values as well as dynamic values like platform properties?

Introducing a new enum is probably best and have the key be the source type of the string (ie: `Raw(String)` or `PlatformPropertyValue(String)`). This might be useful for other weird use cases in the future for metadata injection.
</blockquote></details>

I also have a use for this with the reclient stuff.

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/262)* status: all files reviewed, 7 unresolved discussions (waiting on @allada)

___
*[`cas/worker/running_actions_manager.rs` line 606 at r3](https://reviewable.io/reviews/allada/turbo-cache/262#-Ne9Iip874aP5oT78hEA:-Ne9ObD95mEKIZgkPR58:b5zpzaf) ([raw file](https://github.com/allada/turbo-cache/blob/63c416e50efe1072c1337f9db078e88f1006d5ee/cas/worker/running_actions_manager.rs#L606)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Can we implement `ToString` for `PlatformPropertyValue` then just call `.to_string()` here?
</blockquote></details>

That would make a needless copy though as we only need a `&str`.
___
*[`cas/worker/running_actions_manager.rs` line 607 at r3](https://reviewable.io/reviews/allada/turbo-cache/262#-Ne9HT8h8ZhcsgBa5MnX:-Ne9OjKM1nL_sn8lYeBJ:b-td2emu) ([raw file](https://github.com/allada/turbo-cache/blob/63c416e50efe1072c1337f9db078e88f1006d5ee/cas/worker/running_actions_manager.rs#L607)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This doesn't seem very future proof. I think we should pass all of them even though we only support `Unknown` here. This way if we ever "fix" the properties to be known it won't silently break here.
</blockquote></details>

I'm not sure how we could fix it since it comes from the Protobuf that has no knowledge of the scheduler.
___
*[`cas/worker/tests/running_actions_manager_test.rs` line 141 at r3](https://reviewable.io/reviews/allada/turbo-cache/262#-Ne9JPH7AWU7F1hob6p7:-Ne9OzkK7z7UBYWUcmrY:b-bzeun8) ([raw file](https://github.com/allada/turbo-cache/blob/63c416e50efe1072c1337f9db078e88f1006d5ee/cas/worker/tests/running_actions_manager_test.rs#L141)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit, please put this in the top `use` section.
</blockquote></details>

Editor...
___
*[`config/cas_server.rs` line 328 at r3](https://reviewable.io/reviews/allada/turbo-cache/262#-Ne9L2ti6zCi1BO53IYQ:-Ne9P7tR9ldY_FQkvptT:b-g56n0o) ([raw file](https://github.com/allada/turbo-cache/blob/63c416e50efe1072c1337f9db078e88f1006d5ee/config/cas_server.rs#L328)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This comment looks to be related specifically to platform properties. Can we amend it to be generic, then put the platform property specific stuff in the `EnvironmentSource::Property` comment?
</blockquote></details>

It is generic, I re-worded it specifically for that purpose.

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/262)* status: all files reviewed, 7 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/worker/running_actions_manager.rs` line 606 at r3](https://reviewable.io/reviews/allada/turbo-cache/262#-Ne9Iip874aP5oT78hEA:-Ne9aFnS8zaff9BBWvNI:by8eosu) ([raw file](https://github.com/allada/turbo-cache/blob/63c416e50efe1072c1337f9db078e88f1006d5ee/cas/worker/running_actions_manager.rs#L606)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

That would make a needless copy though as we only need a `&str`.
</blockquote></details>

How about `.to_str()` this would do the same, but without a copy.
___
*[`cas/worker/running_actions_manager.rs` line 607 at r3](https://reviewable.io/reviews/allada/turbo-cache/262#-Ne9HT8h8ZhcsgBa5MnX:-Ne9aXn1B81Svz7SNZGk:bfc452v) ([raw file](https://github.com/allada/turbo-cache/blob/63c416e50efe1072c1337f9db078e88f1006d5ee/cas/worker/running_actions_manager.rs#L607)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

I'm not sure how we could fix it since it comes from the Protobuf that has no knowledge of the scheduler.
</blockquote></details>

It's more about ensuring intended behavior. Maybe one example is if we modify the proto messages to encode this information for inter-system communications and this value no longer publishes. This would be a silent failure. Adding the various properties seems  feels like it would be trivial to maintain (or if we do it via `.to_str()` it won't be an issue).

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/262)* status: all files reviewed, 7 unresolved discussions (waiting on @allada)

___
*[`cas/worker/running_actions_manager.rs` line 606 at r3](https://reviewable.io/reviews/allada/turbo-cache/262#-Ne9Iip874aP5oT78hEA:-Ne9cFFq-TfqJ3KqDmft:b-p570e2) ([raw file](https://github.com/allada/turbo-cache/blob/63c416e50efe1072c1337f9db078e88f1006d5ee/cas/worker/running_actions_manager.rs#L606)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

How about `.to_str()` this would do the same, but without a copy.
</blockquote></details>

Can't be implemented for `Minimum`.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/262)* status: all files reviewed, 7 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/worker/running_actions_manager.rs` line 606 at r3](https://reviewable.io/reviews/allada/turbo-cache/262#-Ne9Iip874aP5oT78hEA:-Ne9cSjDCnt0N261iMWF:b-piblqw) ([raw file](https://github.com/allada/turbo-cache/blob/63c416e50efe1072c1337f9db078e88f1006d5ee/cas/worker/running_actions_manager.rs#L606)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Can't be implemented for `Minimum`.
</blockquote></details>

Hmmm, Maybe use `Cow<'a, str>`?

This way only `Minimum` does an allocation?

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/262)* status: all files reviewed, 4 unresolved discussions (waiting on @allada)

___
*[`cas/worker/running_actions_manager.rs` line 607 at r3](https://reviewable.io/reviews/allada/turbo-cache/262#-Ne9HT8h8ZhcsgBa5MnX:-NeCU7t09GZUexgNQ0Fw:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/63c416e50efe1072c1337f9db078e88f1006d5ee/cas/worker/running_actions_manager.rs#L607)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

It's more about ensuring intended behavior. Maybe one example is if we modify the proto messages to encode this information for inter-system communications and this value no longer publishes. This would be a silent failure. Adding the various properties seems  feels like it would be trivial to maintain (or if we do it via `.to_str()` it won't be an issue).
</blockquote></details>

Done.
___
*[`cas/worker/running_actions_manager.rs` line 1079 at r3](https://reviewable.io/reviews/allada/turbo-cache/262#-Ne9J71JDxJ1NG_UP5X8:-NeCUBWJDcBw_tnekKeM:bchi560) ([raw file](https://github.com/allada/turbo-cache/blob/63c416e50efe1072c1337f9db078e88f1006d5ee/cas/worker/running_actions_manager.rs#L1079)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: I try to ensure all public structs and properties (that are pub as well) are documented.

Can we add a few doc comments here of what this is and it's use?
</blockquote></details>

That's missing for `Callbacks` :wink: 
___
*[`cas/worker/tests/running_actions_manager_test.rs` line 1219 at r3](https://reviewable.io/reviews/allada/turbo-cache/262#-Ne9KGEgBV5VZKyvSkc9:-NeCVjhB6N1u9gA8H6ew:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/63c416e50efe1072c1337f9db078e88f1006d5ee/cas/worker/tests/running_actions_manager_test.rs#L1219)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

It turns out we need to `.flush()` here before we drop the file.

Example: https://github.com/allada/turbo-cache/pull/274/files#diff-88dd8296b1ee148349ea178051ddb0ee927b388cc9a20fdd3979bf0ff9e60895R1116
</blockquote></details>

Done.

**Review by allada — APPROVED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/262)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisstaite-menlo)

___
*[`cas/worker/running_actions_manager.rs` line 1079 at r3](https://reviewable.io/reviews/allada/turbo-cache/262#-Ne9J71JDxJ1NG_UP5X8:-NeDq1Wo0oHS2ImL53ke:b-t5ljgb) ([raw file](https://github.com/allada/turbo-cache/blob/63c416e50efe1072c1337f9db078e88f1006d5ee/cas/worker/running_actions_manager.rs#L1079)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

That's missing for `Callbacks` :wink:
</blockquote></details>

"try" :laughing: 
___
*[`cas/worker/running_actions_manager.rs` line 606 at r4](https://reviewable.io/reviews/allada/turbo-cache/262#-NeDpRyW2M1PfXlAuVQK:-NeDpRyW2M1PfXlAuVQL:b-vdzuwe) ([raw file](https://github.com/allada/turbo-cache/blob/b682a409dd0ac37322553af60bc87fd1afe721d7/cas/worker/running_actions_manager.rs#L606)):*
> ```XML
>                 let value = match source {
>                     EnvironmentSource::Property(property) => {
>                         if let Some(property) = self.action_info.platform_properties.properties.get(property) {
> ```

fyi this might look better:
```rs
self
    .action_info
    .platform_properties
    .properties
    .get(property)
    .map_or_else(|| Cow::Borrowed(""), |v| v.to_str())
```

**Review by allada — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/262#-:-NeDqL2t5U0wp_6wirJc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisstaite-menlo)

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/262)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)

___
*[`cas/worker/running_actions_manager.rs` line 606 at r4](https://reviewable.io/reviews/allada/turbo-cache/262#-NeDpRyW2M1PfXlAuVQK:-NeDqlau7Tx8c2_RkOuh:b5v2zj3) ([raw file](https://github.com/allada/turbo-cache/blob/b682a409dd0ac37322553af60bc87fd1afe721d7/cas/worker/running_actions_manager.rs#L606)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

fyi this might look better:
```rs
self
    .action_info
    .platform_properties
    .properties
    .get(property)
    .map_or_else(|| Cow::Borrowed(""), |v| v.to_str())
```

</blockquote></details>

Certainly does.

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/262)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @chrisstaite-menlo)

**Review by allada — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/262)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)

**Pull request merged**
