### PR TITLE
Move trivial data access Mutex's to sync Mutex.

### PR DESCRIPTION
**Pull request by chrisstaite-menlo**
The Tokio documentation suggests that using an async Mutex for trivial data access (where the data is not required over an `await`) is more expensive and therefore should be avoided.  This is due to the fact that the operations performed while the Mutex is locked are trivial and therefore switching task on the tokio thread is far more inefficient than simply waiting for the Mutex to become available.

See: https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html and https://tokio.rs/tokio/tutorial/shared-state

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/133)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/133)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/worker/running_actions_manager.rs` line 952 at r1](https://reviewable.io/reviews/allada/turbo-cache/133#-NZabox2ATtEMjC_D8Q6:-NZabox2ATtEMjC_D8Q7:b-sh9pyn) ([raw file](https://github.com/allada/turbo-cache/blob/663afd7c9dec15aded137a853f68e4d1d6a780b6/cas/worker/running_actions_manager.rs#L952)):*
> ```XML
>     }
> 
>     fn get_action(&self, action_id: &ActionId) -> Result<Arc<Self::RunningAction>, Error> {
> ```

nit: I was following some code paths and found this entire function is never called.

Can we clean it up here?
___
*[`cas/worker/running_actions_manager.rs` line 966 at r1](https://reviewable.io/reviews/allada/turbo-cache/133#-NZanfGNDkI04edowSF7:-NZanfGNDkI04edowSF8:b-qvnbue) ([raw file](https://github.com/allada/turbo-cache/blob/663afd7c9dec15aded137a853f68e4d1d6a780b6/cas/worker/running_actions_manager.rs#L966)):*
> ```XML
>             running_actions
>                 .iter()
>                 .filter_map(|(_action_id, action)| action.upgrade())
> ```

fyi: This could have been done without creating a `Vec` using:
```rs
.for_each(Self::kill_action)
```
___
*[`cas/worker/running_actions_manager.rs` line 970 at r1](https://reviewable.io/reviews/allada/turbo-cache/133#-NZanOyy--nDukt4_Soo:-NZanOyy--nDukt4_Sop:b-g0dlw1) ([raw file](https://github.com/allada/turbo-cache/blob/663afd7c9dec15aded137a853f68e4d1d6a780b6/cas/worker/running_actions_manager.rs#L970)):*
> ```XML
>         };
>         for action in kill_actions {
>             Self::kill_action(action)
> ```

nit: Lets keep this an await for now because https://github.com/allada/turbo-cache/pull/129#issuecomment-1622058627 Needs to be fixed.

**Review by allada — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/133#-:-NZaqmEa9sydY9pC4rvf:bnfp4nl)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @chrisstaite-menlo)

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/133)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @allada)

___
*[`cas/worker/running_actions_manager.rs` line 966 at r1](https://reviewable.io/reviews/allada/turbo-cache/133#-NZanfGNDkI04edowSF7:-NZarcuP7-Zx7bP6N7G_:bsp807y) ([raw file](https://github.com/allada/turbo-cache/blob/663afd7c9dec15aded137a853f68e4d1d6a780b6/cas/worker/running_actions_manager.rs#L966)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

fyi: This could have been done without creating a `Vec` using:
```rs
.for_each(Self::kill_action)
```
</blockquote></details>

The `Vec` is required to drop the lock.  I tried inlining it with the `for_each` and it looked ugly...

**Review by allada — APPROVED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)

**Pull request merged**
