### PR TITLE
Add blake3 in DedubStore

### PR DESCRIPTION
**Pull request by SpamDoodler**
I don't know how to get the `LAST_CHUNK_HASH` out of the EvictingMap, so the `check_missing_last_chunk_test()` in dedug_store_test fails, however all the other tests are passing successfully.

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205)

### CODE REVIEW

**Review by aaronmondal — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205)* status: all files reviewed, 5 unresolved discussions (waiting on @SpamDoodler)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fItleEmIT3vtLXyWo):*
Typo
___
*[`Cargo.toml` line 60 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fJ7Gd8bQqkA_hDDMt:-N_fJ7Ge-dFPOby7RvL-:b-3px9p9) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/Cargo.toml#L60)):*
> ```TOML
> parking_lot = "0.12.1"
> hashbrown = "0.14"
> blake3="0.1"
> ```

Need most recent version.
___
*[`cas/store/dedup_store.rs` line 185 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fJODE-0l-_Ps2O0er:-N_fJODE-0l-_Ps2O0es:bl4fcui) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L185)):*
> ```XML
>                 JoinHandleDropGuard::new(tokio::spawn(async move {
>                     // let hash = Sha256::digest(&frame[..]);
>                     let hash = *blake3::hash(&frame[..]).as_bytes();
> ```

Is there a way to import this in the header? I.e. in a way similar to the one that sha2 used?
___
*[`cas/store/dedup_store.rs` line 257 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fK4l71zEe3PQPRuay:-N_fK4l71zEe3PQPRuaz:bi4fiyq) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L257)):*
> ```XML
>                 for entry in index_entries.entries {
>                     let first_byte = current_entries_sum;
>                     current_entries_sum += usize::try_from(entry.size_bytes).unwrap();
> ```

Isn't this somewhat risky? if we fail the `try`, what happens?
___
*[`cas/store/tests/dedup_store_test.rs` line 97 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fJctdBfAD0mm59jIj:-N_fJctdBfAD0mm59jIk:bhdo729) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/tests/dedup_store_test.rs#L97)):*
> ```XML
> 
>         // This is the hash & size of the last chunk item in the content_store.
>         // Needs to be recomputed for blake3.
> ```

Apart from this we might want test vectors to test blak3 itself.

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205)* status: all files reviewed, 10 unresolved discussions (waiting on @aaronmondal and @SpamDoodler)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fImtNCZx4YjO_prSS):*
nit: `s/DedubSort/DedupSort`
___
*[`cas/store/dedup_store.rs` line 15 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fKVX26NMFJ8M8hQ9m:-N_fKVX26NMFJ8M8hQ9n:bzfi7h7) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L15)):*
> ```XML
> // limitations under the License.
> 
> #![warn(clippy::all, clippy::pedantic, clippy::nursery)]
> ```

I'd rather not do this yet. I'd rather turn features off in files than turn them on.
___
*[`cas/store/dedup_store.rs` line 92 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fKhnS4fKiXNuVLD5E:-N_fKhnS4fKiXNuVLD5F:bnhdp9v) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L92)):*
> ```XML
>             // We add 30% because the normal_size is not super accurate and we'd prefer to
>             // over estimate than under estimate.
>             // Edit: Do it this way to avoid type conversions.
> ```

nit: Yeah, I knew this could be optimized. But this only happens on construction so I didn't care much.
___
*[`cas/store/dedup_store.rs` line 185 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fJODE-0l-_Ps2O0er:-N_fLMlTDphO552ALFM1:b-4wksjd) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L185)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Is there a way to import this in the header? I.e. in a way similar to the one that sha2 used?
</blockquote></details>

At first I was going to agree, then I read the code. It looks like `blake3::hash()` is more optimized for when you have the entire frame.
___
*[`cas/store/dedup_store.rs` line 257 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fK4l71zEe3PQPRuay:-N_fLuGW2bv2ttOwbjAl:bv73e72) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L257)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Isn't this somewhat risky? if we fail the `try`, what happens?
</blockquote></details>

Yeah, just use `.err_tip(|| "Failed to convert to usize in DedupStore")?`
___
*[`cas/store/dedup_store.rs` line 260 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fM3pR0t3wG38IWMDU:-N_fM3pR0t3wG38IWMDV:b-rqxvo7) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L260)):*
> ```XML
>                     // Filter any items who's end byte is before the first requested byte.
>                     if length.is_some() && current_entries_sum < offset {
>                         start_byte_in_stream += usize::try_from(entry.size_bytes).unwrap();
> ```

ditto.
___
*[`cas/store/dedup_store.rs` line 291 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fM5qW7Lyv5ECQDvph:-N_fM5qW7Lyv5ECQDvpi:b-rqxvo7) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L291)):*
> ```XML
>                             0,
>                             None,
>                             Some(usize::try_from(index_entry.size_bytes).unwrap()),
> ```

ditto.

**Review by allada — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205)* status: all files reviewed, 10 unresolved discussions (waiting on @aaronmondal and @SpamDoodler)

**Comment by SpamDoodler** [comment]
*[`cas/store/dedup_store.rs` line 185 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fJODE-0l-_Ps2O0er:-N_fPEwL348EJIA-lf0M:blnnkil) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L185)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

At first I was going to agree, then I read the code. It looks like `blake3::hash()` is more optimized for when you have the entire frame.
</blockquote></details>

This is also the way the example in the offical rust blake3 repositoty uses.

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205)* status: all files reviewed, 11 unresolved discussions (waiting on @aaronmondal and @SpamDoodler)

___
*[`cas/store/dedup_store.rs` line 185 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fJODE-0l-_Ps2O0er:-N_fRGpJ3U2sUV5TJMTK:b9hffoh) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L185)):*
<details><summary><i>Previously, SpamDoodler wrote…</i></summary><blockquote>

This is also the way the example in the offical rust blake3 repositoty uses.
</blockquote></details>

Yeah, I'd keep it this way.
___
*[`cas/store/dedup_store.rs` line 185 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fRzC70iGTtWTE_DrJ:-N_fRzC70iGTtWTE_DrK:b9yy740) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L185)):*
> ```XML
>                 JoinHandleDropGuard::new(tokio::spawn(async move {
>                     // let hash = Sha256::digest(&frame[..]);
>                     let hash = *blake3::hash(&frame[..]).as_bytes();
> ```

By doing this we "might" be making 2 copies (depending on if the compiler decides to optimize it).

Given that, lets grab the reference and do the deref here:
```
let index_entry = DigestInfo::new(*hash, frame_len as i64);
```

**Comment by SpamDoodler** [comment]
*[`Cargo.toml` line 60 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fJ7Gd8bQqkA_hDDMt:-N_fSycd6FAnfIOCcduO:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/Cargo.toml#L60)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Need most recent version.
</blockquote></details>

Done.

**Comment by SpamDoodler** [comment]
*[`cas/store/dedup_store.rs` line 15 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fKVX26NMFJ8M8hQ9m:-N_fT1_r33xsxPDj8EvY:bss4a2b) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L15)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I'd rather not do this yet. I'd rather turn features off in files than turn them on.
</blockquote></details>

Removed.

**Comment by SpamDoodler** [comment]
*[`cas/store/dedup_store.rs` line 92 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fKhnS4fKiXNuVLD5E:-N_fT55S3DjEttlqYyNw:bkgz56a) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L92)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Yeah, I knew this could be optimized. But this only happens on construction so I didn't care much.
</blockquote></details>

Just thought it's a good idea to explain why I changed it, since it looks a bit ugly.

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205)* status: all files reviewed, 9 unresolved discussions (waiting on @aaronmondal and @SpamDoodler)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fTFnA9fNzX25r89Mv):*
nit: Please squash your commits. I like to keep a good commit history.
___
*[`Cargo.toml` line 60 at r2](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fTOTp08W6V1ufo0zx:-N_fTOTq0Ma8OAq1QJUI:b-qofi02) ([raw file](https://github.com/allada/turbo-cache/blob/e02747c17943a025583baf9a913c70da0fe69a6d/Cargo.toml#L60)):*
> ```TOML
> parking_lot = "0.12.1"
> hashbrown = "0.14"
> blake3="1.4.1"
> ```

nit: space to be consistent
___
*[`cas/store/dedup_store.rs` line 43 at r2](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fTatG4I0Sur-DOLQ4:-N_fTatG4I0Sur-DOLQ5:botusrf) ([raw file](https://github.com/allada/turbo-cache/blob/e02747c17943a025583baf9a913c70da0fe69a6d/cas/store/dedup_store.rs#L43)):*
> ```XML
> const DEFAULT_MAX_CONCURRENT_FETCH_PER_GET: usize = 10;
> 
> #[derive(Serialize, Deserialize, Eq, PartialEq, Debug, Default, Clone)]
> ```

Do we need to `Eq` here? `Eq` on a vector is quite expensive and would rather not tempt people to think it's cheap by allowing `==` operations.

**Comment by SpamDoodler** [comment]
*[`cas/store/dedup_store.rs` line 185 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fRzC70iGTtWTE_DrJ:-N_fTSGX91hRS2KvbPeC:b-idvhcl) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L185)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

By doing this we "might" be making 2 copies (depending on if the compiler decides to optimize it).

Given that, lets grab the reference and do the deref here:
```
let index_entry = DigestInfo::new(*hash, frame_len as i64);
```
</blockquote></details>

I tried that. That doesn't work, since you dereference twice (once in index_entry and once in digest). Note, that these are two copies of the same object as well. I think this is also due to some ownership issue.  One might want to just define that once and clone when passing it to update_oneshot(...).

**Comment by SpamDoodler** [comment]
*[`cas/store/dedup_store.rs` line 257 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fK4l71zEe3PQPRuay:-N_fUoFw9sB_EonxRxP3:b-rlogxf) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L257)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Yeah, just use `.err_tip(|| "Failed to convert to usize in DedupStore")?`
</blockquote></details>

I like that!

**Comment by SpamDoodler** [comment]
*[`cas/store/tests/dedup_store_test.rs` line 97 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fJctdBfAD0mm59jIj:-N_fVITk54rAqRliH-pq:bw9tbu3) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/tests/dedup_store_test.rs#L97)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Apart from this we might want test vectors to test blak3 itself.
</blockquote></details>

Maybe.

**Comment by SpamDoodler** [comment]
*[`cas/store/dedup_store.rs` line 43 at r2](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fTatG4I0Sur-DOLQ4:-N_fV1Sv0i5DGRAG2NyJ:bpexz5h) ([raw file](https://github.com/allada/turbo-cache/blob/e02747c17943a025583baf9a913c70da0fe69a6d/cas/store/dedup_store.rs#L43)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Do we need to `Eq` here? `Eq` on a vector is quite expensive and would rather not tempt people to think it's cheap by allowing `==` operations.
</blockquote></details>

The linter complained about this. However, I think you are right and we should not use it here. I'll remove it.

**Comment by SpamDoodler** [comment]
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fTFnA9fNzX25r89Mv):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Please squash your commits. I like to keep a good commit history.
</blockquote></details>

Done.

**Comment by SpamDoodler** [comment]
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fItleEmIT3vtLXyWo):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Typo
</blockquote></details>

fixed by squash

**Comment by SpamDoodler** [comment]
*[`Cargo.toml` line 60 at r2](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fTOTp08W6V1ufo0zx:-N_f_BS53Auei9wJEECP:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/e02747c17943a025583baf9a913c70da0fe69a6d/Cargo.toml#L60)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: space to be consistent
</blockquote></details>

Done.

**Review by aaronmondal — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205)* status: all files reviewed, 2 unresolved discussions (waiting on @allada)

**Comment by SpamDoodler** [comment]
*[`cas/store/dedup_store.rs` line 185 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fRzC70iGTtWTE_DrJ:-N_fatvl3Ymufd4eRgDs:bn7nkyq) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L185)):*
<details><summary><i>Previously, SpamDoodler wrote…</i></summary><blockquote>

I tried that. That doesn't work, since you dereference twice (once in index_entry and once in digest). Note, that these are two copies of the same object as well. I think this is also due to some ownership issue.  One might want to just define that once and clone when passing it to update_oneshot(...).
</blockquote></details>

I changed that. Removed all doublelings.

**Comment by SpamDoodler** [comment]
*[`cas/store/dedup_store.rs` line 185 at r1](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fJODE-0l-_Ps2O0er:-N_fVC5-A4k_O2jjxQYV:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/773a730c33f7dbc8680d88bb1c7df8bcee8b385d/cas/store/dedup_store.rs#L185)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Yeah, I'd keep it this way.
</blockquote></details>

Done.

**Review by allada — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205)* status: all files reviewed, 1 unresolved discussion (waiting on @SpamDoodler)

**Review by allada — COMMENTED** [review]
You'll also need to rebase then regen the toml files.

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205#-:-N_fbTEE3qWYIGPErRPP:b-3owxel)* status: all files reviewed, 1 unresolved discussion (waiting on @SpamDoodler)

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205)* status: 1 of 23 files reviewed, 2 unresolved discussions (waiting on @aaronmondal and @SpamDoodler)

___
*[`-- commits` line 1 at r4](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fetNyE1XOiw8Ru7xO):*
I think your rebase didn't go quite so well...

Use `git reflog` to find the previous hash then `git reset {HASH_HERE} --hard` to it.

Then `git rebase upstream/master`

In this case (unique to this PR) don't resolve any conflicts, just run:
`git add .`
`git rebase --continue`

Then run `CARGO_BAZEL_REPIN=1 bazel sync --only=crate_index`
Then `git add .`
Then `git commit --amend`

And save the changes.

This should get you what you want.

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205)* status: 1 of 23 files reviewed, 2 unresolved discussions (waiting on @aaronmondal and @SpamDoodler)

___
*[`-- commits` line 1 at r4](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fetNyE1XOiw8Ru7xO):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I think your rebase didn't go quite so well...

Use `git reflog` to find the previous hash then `git reset {HASH_HERE} --hard` to it.

Then `git rebase upstream/master`

In this case (unique to this PR) don't resolve any conflicts, just run:
`git add .`
`git rebase --continue`

Then run `CARGO_BAZEL_REPIN=1 bazel sync --only=crate_index`
Then `git add .`
Then `git commit --amend`

And save the changes.

This should get you what you want.
</blockquote></details>

If the REPIN does not work, check your toml file, and fix it manually, then re-run the repin.

**Review by SpamDoodler — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205#-:-N_fecQqBB5Wh3oyiRKW:b-896fix)* status: 1 of 23 files reviewed, 2 unresolved discussions (waiting on @aaronmondal and @allada)

___
*[`-- commits` line 1 at r4](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fetNyE1XOiw8Ru7xO):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

If the REPIN does not work, check your toml file, and fix it manually, then re-run the repin.
</blockquote></details>

Yeah, sorry. I did rebuild during the process and messed up the lockfiles. It should be fine now.

**Review by allada — APPROVED** [review]
> Reviewed 4 of 22 files at r4, 18 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205)* status: all files reviewed, 4 unresolved discussions (waiting on @SpamDoodler)

___
*[`-- commits` line 4 at r5](https://reviewable.io/reviews/allada/turbo-cache/205#-N_ffjLbCqRGvD0JyS8o):*
nit: This comment is leftover from your rebase, please remove it.
___
*[`Cargo.toml` line 65 at r5](https://reviewable.io/reviews/allada/turbo-cache/205#-N_ffq-1CUCVF75Ifj_C:-N_ffq-1CUCVF75Ifj_D:b-y2dkq8) ([raw file](https://github.com/allada/turbo-cache/blob/5c49557e398bf7a273b4bb59ea06bad28eee4125/Cargo.toml#L65)):*
> ```TOML
> prometheus-client = "0.21.2"
> blake3 = "1.4.1"
> ```

nit: extra new line.
___
*[`cas/store/dedup_store.rs` line 181 at r5](https://reviewable.io/reviews/allada/turbo-cache/205#-N_ffwxD4kIY8q45ShEw:-N_ffwxD4kIY8q45ShEx:b-8y4o0n) ([raw file](https://github.com/allada/turbo-cache/blob/5c49557e398bf7a273b4bb59ea06bad28eee4125/cas/store/dedup_store.rs#L181)):*
> ```XML
>             spawns.push(
>                 JoinHandleDropGuard::new(tokio::spawn(async move {
>                     // let hash = Sha256::digest(&frame[..]);
> ```

nit: Useless comment.
___
*[`cas/store/dedup_store.rs` line 185 at r5](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fg4hbABcf6t267Ejt:-N_fg4hbABcf6t267Eju:b-8y4o0n) ([raw file](https://github.com/allada/turbo-cache/blob/5c49557e398bf7a273b4bb59ea06bad28eee4125/cas/store/dedup_store.rs#L185)):*
> ```XML
>                     let index_entry = DigestInfo::new(hash.into(), frame.len() as i64);
>                     let content_store_pin = Pin::new(content_store.as_ref());
>                     // let digest = DigestInfo::new(hash, frame.len() as i64);
> ```

nit: Useless comment.

**Review by SpamDoodler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205)* status: 21 of 23 files reviewed, 4 unresolved discussions (waiting on @allada)

___
*[`-- commits` line 4 at r5](https://reviewable.io/reviews/allada/turbo-cache/205#-N_ffjLbCqRGvD0JyS8o):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: This comment is leftover from your rebase, please remove it.
</blockquote></details>

Gone.
___
*[`Cargo.toml` line 65 at r5](https://reviewable.io/reviews/allada/turbo-cache/205#-N_ffq-1CUCVF75Ifj_C:-N_fhg40CO-0v3q3JyFR:b-87j1qu) ([raw file](https://github.com/allada/turbo-cache/blob/5c49557e398bf7a273b4bb59ea06bad28eee4125/Cargo.toml#L65)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: extra new line.
</blockquote></details>

Gone.
___
*[`cas/store/dedup_store.rs` line 181 at r5](https://reviewable.io/reviews/allada/turbo-cache/205#-N_ffwxD4kIY8q45ShEw:-N_fhbgLAiNfPiHaAtBW:b-87j1qu) ([raw file](https://github.com/allada/turbo-cache/blob/5c49557e398bf7a273b4bb59ea06bad28eee4125/cas/store/dedup_store.rs#L181)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Useless comment.
</blockquote></details>

Gone.
___
*[`cas/store/dedup_store.rs` line 185 at r5](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fg4hbABcf6t267Ejt:-N_fhed33EMOUCrQcz3Y:b-87j1qu) ([raw file](https://github.com/allada/turbo-cache/blob/5c49557e398bf7a273b4bb59ea06bad28eee4125/cas/store/dedup_store.rs#L185)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Useless comment.
</blockquote></details>

Gone.

**Review by aaronmondal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205)* status: all files reviewed, 5 unresolved discussions (waiting on @allada and @SpamDoodler)

___
*[`-- commits` line 2 at r6](https://reviewable.io/reviews/allada/turbo-cache/205#-N_fhowK7bb9k5m_dzTR):*
Would be nice to have a snon-empty commit message. If someone goes through the commit history to find out why this was added, they should get a brief overview of the motivation behind this change without having to dig through the repo.

**Review by aaronmondal — APPROVED** [review]
Thanks a lot for this change! Let's try CI to see whether it passes.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205#-:-N_flLxg064StT_nduNa:b-npexkb)* status: all files reviewed, 4 unresolved discussions (waiting on @allada)

**Review by allada — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SpamDoodler)

**Review by allada — APPROVED** [review]
It looks like you need to extract the new golden value from the dedup store. I'd do this by adding a:
```rs
index_entries.for_each(|v| println!("{}", v.str()));
```

The last hash it produces should be the one you want to replace in the test.

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205#-:-N_fqn-K4OXuejdBMIuo:bnqn8ah)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SpamDoodler)

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205#-:-N_pnV-I7IeYsekLG1iN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SpamDoodler)

**Review by allada — APPROVED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/205)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SpamDoodler)

**Pull request merged**
