### PR TITLE
improve clarity for getting started.

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
very minor change to improve clarity.

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/249)

### CODE REVIEW

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/249)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @MarcusSorealheis)

___
*[`-- commits` line 1 at r3](https://reviewable.io/reviews/allada/turbo-cache/249#-Ndp7qfM99BxnRxaq_T0):*
Please squash your commits into a single commit.

**Comment by MarcusSorealheis** [comment]
> > Reviewed 1 of 1 files at r3.
> > _[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/249)_ status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @MarcusSorealheis)
> 
> _[`-- commits` line 1 at r3](https://reviewable.io/reviews/allada/turbo-cache/249#-Ndp7qfM99BxnRxaq_T0):_ Please squash your commits into a single commit.

I addressed the comments. Thank you for taking a look.

**Review by allada — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/249)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarcusSorealheis)

**Review by allada — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/249#-:-Ne-1R2vDUHw342K57TC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarcusSorealheis)

**Pull request merged**
