### PR TITLE
Fixes the `entrypoint_cmd` configuration

### PR DESCRIPTION
**Pull request by allada**
Fixes an oversight where the design called for `entrypoint_cmd` config, but it was never implemented.

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/139)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/139#-:-NZiXXrn4w3IcFurweFT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Review by chrisstaite-menlo — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/139)* status: all files reviewed, 1 unresolved discussion (waiting on @allada)

___
*[`config/cas_server.rs` line 288 at r3](https://reviewable.io/reviews/allada/turbo-cache/139#-NZjQmHRAEsZrtMg_Fc7:-NZjQmHS9e8jxnAv_LaE:b-3ndyhi) ([raw file](https://github.com/allada/turbo-cache/blob/297750fd003cbfc8de5fab354030187cb9dbafaa/config/cas_server.rs#L288)):*
> ```XML
>     /// '$@' has a special meaning in that all the arguments will expand into this
>     /// location.
>     /// Example: "run.sh $@" and a job with command: "sleep 5" will result in a
> ```

Is it worth adding a comment that this isn't yet supported?

**Review by allada — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/139)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisstaite-menlo)

___
*[`config/cas_server.rs` line 288 at r3](https://reviewable.io/reviews/allada/turbo-cache/139#-NZjQmHRAEsZrtMg_Fc7:-NZlWWYF03BCNnr5_vi5:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/297750fd003cbfc8de5fab354030187cb9dbafaa/config/cas_server.rs#L288)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Is it worth adding a comment that this isn't yet supported?
</blockquote></details>

Done.

**Review by chrisstaite-menlo — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/139)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Review by allada — COMMENTED** [review]
> Reviewed 3 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/139)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Pull request merged**
