### PR TITLE
Cache worker results

### PR DESCRIPTION
**Pull request by chrisstaite-menlo**
This is a replacement for half of #135 where the workers store the action results in the action cache when they are done.

There will be another PR that will cover the case required for Goma where results will be looked up in the AC before they are scheduled as a new job.

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/142)

### CODE REVIEW

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/142)* status: 0 of 12 files reviewed, 2 unresolved discussions

___
*[`Cargo.toml` line 30 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZlF_5w99TEH2ThxZ_-:-NZlF_5w99TEH2ThxZ_0:bqxitih) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/Cargo.toml#L30)):*
> ```TOML
> futures = "0.3.17"
> tokio = { version = "1.26.0", features = ["macros", "io-util", "fs", "rt-multi-thread", "parking_lot"] }
> tokio-stream = { version = "0.1.8", features = ["fs", "sync", "net"] }
> ```

This feature is only required in dev (to allow a random TCP port to serve a GrpcStore).  I'm not sure how to turn a feature on for dev only, so I have put it here...
___
*[`cas/grpc_service/BUILD` line 25 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZlFy8h39ANfgp_fKWA:-NZlFy8h39ANfgp_fKWB:bcqcgl8) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/grpc_service/BUILD#L25)):*
> ```Starlark
>     name = "ac_server",
>     srcs = ["ac_server.rs"],
>     visibility = ["//cas:__pkg__", "//cas/worker:__pkg__"],
> ```

Not sure if there's a better way to make this available for use in testing only?

**Comment by chrisstaite** [comment]
I'm not familiar with the other use cases here, should the ac_store for workers also be optional?  If so, I had code for that in the previous PR, so I can just bring it in.

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/142)* status: 8 of 12 files reviewed, 15 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/grpc_service/BUILD` line 25 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZlFy8h39ANfgp_fKWA:-NZlYQTw8KVZKnS20Gq_:b-ym3y3i) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/grpc_service/BUILD#L25)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Not sure if there's a better way to make this available for use in testing only?
</blockquote></details>

You could specify the precise test instead.
___
*[`cas/scheduler/action_messages.rs` line 575 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnHHO84rtHxqKZQDrx:-NZnHHO84rtHxqKZQDry:b-9qbp2i) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/scheduler/action_messages.rs#L575)):*
> ```XML
>             // Handled separately as there are no server logs and the action
>             // result is already in Proto format.
>             ActionStage::CompletedFromCache(action_result) => {
> ```

nit: Please rename `action_result` to `proto_action_result`.
___
*[`cas/scheduler/action_messages.rs` line 587 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnGT-w4ix44ZJ7aQHH:-NZnGT-w4ix44ZJ7aQHI:b-53u78t) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/scheduler/action_messages.rs#L587)):*
> ```XML
> 
>         let mut server_logs = HashMap::with_capacity(action_result.server_logs.len());
>         for (k, v) in &action_result.server_logs {
> ```

I feel serving the `server_logs` of the task that was executed even on cached actions could be useful. At least, do you see a reason it is a bad idea?
___
*[`cas/scheduler/action_messages.rs` line 589 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnFZ118TpZDetYe7EX:-NZnFZ118TpZDetYe7EY:b-qylxvz) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/scheduler/action_messages.rs#L589)):*
> ```XML
>         for (k, v) in &action_result.server_logs {
>             server_logs.insert(
>                 k.to_owned(),
> ```

super nit: I prefer using `.clone()` over `.to_owned()` just to hint that nothing special is happening, since `clone()` is usually more simple and generic.
___
*[`cas/worker/local_worker.rs` line 158 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnLEaFEnuHLHWcK9qg:-NZnLEaFEnuHLHWcK9qh:bowedu) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/local_worker.rs#L158)):*
> ```XML
>                                 );
> 
>                             let store_manager = self.running_actions_manager.clone();
> ```

nit: Can we rename this `running_actions_manager`? `store_manager` does not describe it very well imo. :smile: 
___
*[`cas/worker/local_worker.rs` line 164 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnO0_nAWiIvbOwFvnm:-NZnO0_nAWiIvbOwFvnn:b60hw7m) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/local_worker.rs#L164)):*
> ```XML
>                                         // Save in the action cache before notifying the scheduler that we've completed.
>                                         if let Some(digest_info) = action_digest.clone().and_then(|action_digest| action_digest.try_into().ok()) {
>                                             if store_manager.save_action_in_store(digest_info, action_result.clone()).await.is_err() {
> ```

nit:
```rs
 if let Err(err) = store_manager.save_action_in_store(digest_info, action_result.clone()).await {
  log::error!("\x1b[0;31mError saving action in store\x1b[0m: {} - {:?}", err, action_digest);
}

```
___
*[`cas/worker/local_worker.rs` line 164 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnOnfGEdQY-3eziN03:-NZnOnfGEdQY-3eziN04:bb3u8hz) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/local_worker.rs#L164)):*
> ```XML
>                                         // Save in the action cache before notifying the scheduler that we've completed.
>                                         if let Some(digest_info) = action_digest.clone().and_then(|action_digest| action_digest.try_into().ok()) {
>                                             if store_manager.save_action_in_store(digest_info, action_result.clone()).await.is_err() {
> ```

Lets put this behind an enum flag of:

```rs
enum UploadCacheResultsStrategy {
  #[default]
  SuccessOnly,
  Never,
  Everything,
}
```

And by default only upload results that did not have an error.
___
*[`cas/worker/local_worker.rs` line 176 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnQ7GC9TGuDWbtywim:-NZnQ7GC9TGuDWbtywin:b-s355j3) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/local_worker.rs#L176)):*
> ```XML
>                                             }
>                                         )
>                                         .await
> ```

nit: Nothing in the spec says that we need to cache the results, and nothing in the spec says that we 
___
*[`cas/worker/running_actions_manager.rs` line 971 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnKg5B5679j2Hlh-90:-NZnKg5C8yQp0r1ibpiX:b-puf93k) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/running_actions_manager.rs#L971)):*
> ```XML
>     }
> 
>     async fn save_action_in_store(&self, action_digest: DigestInfo, action_result: ActionResult) -> Result<(), Error> {
> ```

nit: Can we rename this `cache_action_results` or `upload_cached_action_results`?
___
*[`cas/worker/running_actions_manager.rs` line 972 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnKRMC-6ehpI75VNTs:-NZnKRMC-6ehpI75VNTt:b-5dnu3x) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/running_actions_manager.rs#L972)):*
> ```XML
> 
>     async fn save_action_in_store(&self, action_digest: DigestInfo, action_result: ActionResult) -> Result<(), Error> {
>         let mut store_data = BytesMut::with_capacity(ESTIMATED_DIGEST_SIZE);
> ```

nit: We don't need this unless we are not a gRPC store.
___
*[`cas/worker/running_actions_manager.rs` line 987 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnKACcBEAA19O9gENS:-NZnKACcBEAA19O9gENT:bxkii6s) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/running_actions_manager.rs#L987)):*
> ```XML
>             };
>             grpc_store
>                 .update_action_result(Request::new(update_action_request))
> ```

It looks like we can use this function unconditionally since it's a part of the `ActionCache` interface.
___
*[`cas/worker/running_actions_manager.rs` line 989 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnKqTY-jD2yZq7Xfp0:-NZnKqTY-jD2yZq7Xfp1:b-jbb9y3) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/running_actions_manager.rs#L989)):*
> ```XML
>                 .update_action_result(Request::new(update_action_request))
>                 .await
>                 .map(|_| ())?;
> ```

nit: When using `?` please use `.err_tip()` to add a little more context on where the error came from. This makes debugging a little less hell when something goes wrong.
___
*[`cas/worker/running_actions_manager.rs` line 993 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnL5E94G__BCU6owIn:-NZnL5E94G__BCU6owIo:b-5v3gaq) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/running_actions_manager.rs#L993)):*
> ```XML
>             Pin::new(self.ac_store.as_ref())
>                 .update_oneshot(action_digest.clone(), store_data.freeze())
>                 .await?;
> ```

nit: ditto.
___
*[`cas/worker/tests/running_actions_manager_test.rs` line 935 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnTSan9hmUk8YXI9fD:-NZnTSan9hmUk8YXI9fE:br5tng8) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/tests/running_actions_manager_test.rs#L935)):*
> ```XML
> 
>     #[tokio::test]
>     async fn save_action_in_grpc_store() -> Result<(), Box<dyn std::error::Error>> {
> ```

I would rather not test this branch right now unless you really feel we need too.

My rationale is that it is a simple forward so it's unlikely to be buggy. In addition I believe the bloat this test brings is greater than the chances of the `grpc` hot path failing.

**Review by allada — COMMENTED** [review]
I don't think we need to make it optional. I think this is really close to being just fine. I was thinking if the scheduler should be the one to upload the action cache results, so we could get a new task on the node faster, but then after thinking about it, it'd be better to solve this dead time another way (maybe by allowing the next task to start downloading while the last task is uploading).

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/142#-:-NZnUYKN7wCS9Ifd-yBY:bf59eqm)* status: 8 of 12 files reviewed, 15 unresolved discussions (waiting on @chrisstaite-menlo)

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/142)* status: 8 of 12 files reviewed, 5 unresolved discussions (waiting on @allada)

___
*[`cas/scheduler/action_messages.rs` line 587 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnGT-w4ix44ZJ7aQHH:-NZpVAwx0QpsPfHTVixi:bayt8mx) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/scheduler/action_messages.rs#L587)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I feel serving the `server_logs` of the task that was executed even on cached actions could be useful. At least, do you see a reason it is a bad idea?
</blockquote></details>

The issue is that the `ActionResult` doesn't have the `server_logs` in it.  That's a separate entry as part of `ExecuteResponse`.
___
*[`cas/worker/local_worker.rs` line 176 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnQ7GC9TGuDWbtywim:-NZpXOMjAhsV6apqXzKX:b-w5ugq) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/local_worker.rs#L176)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Nothing in the spec says that we need to cache the results, and nothing in the spec says that we 
</blockquote></details>

I feel like this comment wasn't finished.
___
*[`cas/worker/running_actions_manager.rs` line 987 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnKACcBEAA19O9gENS:-NZpbCRs2uKjgNS1HbHY:b-azj426) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/running_actions_manager.rs#L987)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

It looks like we can use this function unconditionally since it's a part of the `ActionCache` interface.
</blockquote></details>

I've been looking at this and `Store` doesn't implement `ActionCache`. Only the `AcServer` implements it.  This means that we can't have a local action cache.  I think I'll leave it as it is.
___
*[`cas/worker/tests/running_actions_manager_test.rs` line 935 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnTSan9hmUk8YXI9fD:-NZpc3J_359SKZctQL6p:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/tests/running_actions_manager_test.rs#L935)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I would rather not test this branch right now unless you really feel we need too.

My rationale is that it is a simple forward so it's unlikely to be buggy. In addition I believe the bloat this test brings is greater than the chances of the `grpc` hot path failing.
</blockquote></details>

Done.

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/142)* status: 2 of 13 files reviewed, 5 unresolved discussions (waiting on @allada)

___
*[`cas/worker/local_worker.rs` line 164 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnOnfGEdQY-3eziN03:-NZpcA9B8IVn0Mz-yz0S:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/local_worker.rs#L164)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Lets put this behind an enum flag of:

```rs
enum UploadCacheResultsStrategy {
  #[default]
  SuccessOnly,
  Never,
  Everything,
}
```

And by default only upload results that did not have an error.
</blockquote></details>

Done.

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/142#-:-NZs65C7A7ehl0gsdqME:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/worker/local_worker.rs` line 176 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnQ7GC9TGuDWbtywim:-NZrB9iY01LC6WtCBu42:b1z93gt) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/local_worker.rs#L176)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

I feel like this comment wasn't finished.
</blockquote></details>

yeah, my bad. Ignore this. Something I was thinking then realized it was a bad idea.
___
*[`cas/worker/running_actions_manager.rs` line 987 at r1](https://reviewable.io/reviews/allada/turbo-cache/142#-NZnKACcBEAA19O9gENS:-NZs3-P36i4E8AVruN6c:b2wigt8) ([raw file](https://github.com/allada/turbo-cache/blob/4d2f3d5ca0094b567e079d1e45867b149a5c58ad/cas/worker/running_actions_manager.rs#L987)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

I've been looking at this and `Store` doesn't implement `ActionCache`. Only the `AcServer` implements it.  This means that we can't have a local action cache.  I think I'll leave it as it is.
</blockquote></details>

I see, for some reason I was thinking it was an `AcServer`.
___
*[`cas/worker/tests/running_actions_manager_test.rs` line 127 at r2](https://reviewable.io/reviews/allada/turbo-cache/142#-NZs5yPgEXR4F3Cz1pfA:-NZs5yPgEXR4F3Cz1pfB:bjznigq) ([raw file](https://github.com/allada/turbo-cache/blob/c2b1436e86bed9ffa28511b131078d908726f5b1/cas/worker/tests/running_actions_manager_test.rs#L127)):*
> ```XML
>     #[tokio::test]
>     async fn download_to_directory_file_download_test() -> Result<(), Box<dyn std::error::Error>> {
>         let (fast_store, slow_store, cas_store, _) = setup_stores().await?;
> ```

very nit: Can we make this `_ac_store`?
___
*[`cas/worker/tests/running_actions_manager_test.rs` line 219 at r2](https://reviewable.io/reviews/allada/turbo-cache/142#-NZs60cu4m-QsSh3mioh:-NZs60cu4m-QsSh3mioi:bsvg6pq) ([raw file](https://github.com/allada/turbo-cache/blob/c2b1436e86bed9ffa28511b131078d908726f5b1/cas/worker/tests/running_actions_manager_test.rs#L219)):*
> ```XML
>     #[tokio::test]
>     async fn download_to_directory_folder_download_test() -> Result<(), Box<dyn std::error::Error>> {
>         let (fast_store, slow_store, cas_store, _) = setup_stores().await?;
> ```

very nit: ditto.
___
*[`cas/worker/tests/running_actions_manager_test.rs` line 886 at r2](https://reviewable.io/reviews/allada/turbo-cache/142#-NZs5MLF6GVOr2ndYXMM:-NZs5MLF6GVOr2ndYXMN:b-y73guf) ([raw file](https://github.com/allada/turbo-cache/blob/c2b1436e86bed9ffa28511b131078d908726f5b1/cas/worker/tests/running_actions_manager_test.rs#L886)):*
> ```XML
> 
>     #[tokio::test]
>     async fn save_action_in_memory_store() -> Result<(), Box<dyn std::error::Error>> {
> ```

nit: I think this should be `caches_results_in_action_cache_store`.
___
*[`cas/worker/tests/running_actions_manager_test.rs` line 936 at r2](https://reviewable.io/reviews/allada/turbo-cache/142#-NZs5YZSBY6ePEY4Lt_t:-NZs5YZSBY6ePEY4Lt_u:b-jcn6ai) ([raw file](https://github.com/allada/turbo-cache/blob/c2b1436e86bed9ffa28511b131078d908726f5b1/cas/worker/tests/running_actions_manager_test.rs#L936)):*
> ```XML
> 
>     #[tokio::test]
>     async fn save_failed_action_in_memory_store() -> Result<(), Box<dyn std::error::Error>> {
> ```

nit: I think this should be `failed_action_does_not_cache_in_action_cache`.

**Comment by chrisstaite** [comment]
Any ideas why dummy_test_sh is hanging in the integration tests?

**Comment by chrisstaite-menlo** [comment]
Missing `#[serde(default)]` again... should be fixed now.

**Pull request merged**
