### PR TITLE
Implement fast slow metrics.

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
Register the fast and slow metrics.

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/263)

### CODE REVIEW

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/263#-:-Ndvj1cN5WDMSR29CzlQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarcusSorealheis)

**Comment by MarcusSorealheis** [comment]
Closes: #256

**Review by allada — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarcusSorealheis)

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/263)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @MarcusSorealheis)

**Review by allada — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarcusSorealheis)

**Pull request merged**
