### PR TITLE
Add support to build with Cargo

### PR DESCRIPTION
**Pull request by allada**
Adds the ability to build both with Bazel and Cargo. Bazel will still be the primary and Cargo will be the secondary. All files required by Cargo will be generated from Bazel.

closes: #231

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/233)

### CODE REVIEW

**Comment by allada** [comment]
@aaronmondal It turns out it was not too difficult to make all tests, binaries and libraries supported with cargo.

If you could, would you mind reviewing the changes?

**Review by aaronmondal — CHANGES_REQUESTED** [review]
Pretty much LGTM. Very interesting approach.

One thing I'd consider as future change is to somehow incorporate the generation of the `gencargo` directory in the build so that one doesn't need to track changes to it in git (and so that one can avoid updating it). While I'm usually not a big fan of having a dedicated `build.sh` script, in this case it might make sense since this is a "secondary-ish" build next to the Bazel build. Maybe something like `build_cargo_windows.bat`/`build_cargo_unix.sh`?

> Reviewed 14 of 100 files at r1, 86 of 87 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/233#-:-Nc2Rb9C2_BMsu0ijS40:b-fln0p)* status: all files reviewed, 4 unresolved discussions (waiting on @allada)

___
*[`README.md` line 28 at r3](https://reviewable.io/reviews/allada/turbo-cache/233#-Nc2Nx370omPIGrCoaIl:-Nc2Nx370omPIGrCoaIm:bhqa5xt) ([raw file](https://github.com/allada/turbo-cache/blob/3220392210e97f0b15c0c6f31f47f4a5c32a8800/README.md#L28)):*
> ```Markdown
> bazel test //... \
>   --remote_instance_name=main \
>   --remote_cache=grpc://127.0.0.1:50051 \
> ```

Don't the remote cache and the remote executor usually use two different ports?
___
*[`WORKSPACE` line 52 at r3](https://reviewable.io/reviews/allada/turbo-cache/233#-Nc2OhmM3tekk6Mwyv2d:-Nc2OhmM3tekk6Mwyv2e:b-ziel29) ([raw file](https://github.com/allada/turbo-cache/blob/3220392210e97f0b15c0c6f31f47f4a5c32a8800/WORKSPACE#L52)):*
> ```Starlark
>     lockfile = "//:Cargo.Bazel.lock",
>     packages = {
>         name: crate.spec(
> ```

Oh this is a nice pattern!
___
*[`proto/genproto/lib.rs` line 16 at r3](https://reviewable.io/reviews/allada/turbo-cache/233#-Nc2QA1D-UbPfjFnaPHL:-Nc2QA1D-UbPfjFnaPHM:beys534) ([raw file](https://github.com/allada/turbo-cache/blob/3220392210e97f0b15c0c6f31f47f4a5c32a8800/proto/genproto/lib.rs#L16)):*
> ```XML
> 
> // *** DO NOT MODIFY ***
> // This file is auto-generated to provide the libs for the proto files.
> ```

Probably a good idea to say which tool did the autogeneration (This file is auto-generated by ... ) so that someone unfamiliar with the details of the autogeneration pipeline knows where to look.
___
*[`tools/build_cargo_manifest.py` line 27 at r3](https://reviewable.io/reviews/allada/turbo-cache/233#-Nc2Qooc-jO_vwcTbsfd:-Nc2Qooc-jO_vwcTbsfe:b-k1jqqq) ([raw file](https://github.com/allada/turbo-cache/blob/3220392210e97f0b15c0c6f31f47f4a5c32a8800/tools/build_cargo_manifest.py#L27)):*
> ```Python
> 
> ROOT_DIR = os.path.normpath(os.path.dirname(os.path.realpath(__file__)) + '/..')
> # This is some voodo magic that trates packages.bzl as a python module.
> ```

treats

**Review by allada — COMMENTED** [review]
> Dismissed @aaronmondal from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/233)* status: 101 of 104 files reviewed, all discussions resolved (waiting on @aaronmondal)

**Review by allada — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/233)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Pull request merged**
