### PR TITLE
Add prometheus publishing and hook up FilesystemStore

### PR DESCRIPTION
**Pull request by allada**
Defines the framework for publishing metrics through prometheus
and seed the implementation with stats on FilesystemStore and
EvictionMap.

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/202)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@chrisstaite-menlo 

Took me a while to get an API i liked, very happy with the way it turned out.

I'll write tests after some comments on reviews.

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/202#-:-N_adtQI4SC4puSUX3I1:b-t1ykil)* status: 0 of 18 files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/202)* status: all files reviewed, 3 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/cas_main.rs` line 65 at r2](https://reviewable.io/reviews/allada/turbo-cache/202#-N_dRY338FMYOYfxOreq:-N_dkCj128fHHyJHB0w0:b-c0jmi9) ([raw file](https://github.com/allada/turbo-cache/blob/472764f19a235610eac7b62cbf89556e66ac1eab/cas/cas_main.rs#L65)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

What's the `<>` around Registry here?
</blockquote></details>

It tells rust to use default template arguments.
___
*[`config/examples/basic_cas.json` line 21 at r2](https://reviewable.io/reviews/allada/turbo-cache/202#-N_dSQ272oVgPplo_zBx:-N_dkIt9E48fueGMeqCz:bc7527a) ([raw file](https://github.com/allada/turbo-cache/blob/472764f19a235610eac7b62cbf89556e66ac1eab/config/examples/basic_cas.json#L21)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Was this swap on purpose?  Seems unrelated.
</blockquote></details>

yeah, it's actually wrong. The slow is memory and the fast is filesystem for some reason. This fixes it.
___
*[`integration_tests/simple_prometheus_test.sh` line 2 at r2](https://reviewable.io/reviews/allada/turbo-cache/202#-N_dSWCl4sZNw1tMGQn6:-N_dkWaq7uaYUgjXEJdU:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/472764f19a235610eac7b62cbf89556e66ac1eab/integration_tests/simple_prometheus_test.sh#L2)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

2023
</blockquote></details>

Done.
___
*[`util/evicting_map.rs` line 303 at r2](https://reviewable.io/reviews/allada/turbo-cache/202#-N_dSsd6-h1UXzT6crLG:-N_dkxns2H2KPeRM8Yd6:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/472764f19a235610eac7b62cbf89556e66ac1eab/util/evicting_map.rs#L303)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Is it worth caching the result of `entry.data.len()` in case it's an expensive operation?
</blockquote></details>

Done.

**Review by chrisstaite-menlo — APPROVED** [review]
> Reviewed 21 of 21 files at r3, 21 of 21 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/202)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Review by allada — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/202)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Pull request merged**
