### PR TITLE
Implement Into traits indirectly via From

### PR DESCRIPTION
**Pull request by aaronmondal**
Also addresses most clippy warnings related to these files as long as they don't affect other files too much.

The impls that could panic should be implemented via TryFrom, but changing this would affect more files. For now, keep it as From and change those in the future.

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/158)

### CODE REVIEW

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/158#-:-NZy0Okk9EXis7F2ThXa:bnfp4nl)* status: all files reviewed, 11 unresolved discussions (waiting on @aaronmondal)

___
*[`cas/scheduler/action_messages.rs` line 275 at r1](https://reviewable.io/reviews/allada/turbo-cache/158#-NZxyjwHAKbLCfey-ocS:-NZxyjwHAKbLCfey-ocT:bcxyiuw) ([raw file](https://github.com/allada/turbo-cache/blob/f946cd0803262d0a439138258d690090e77c03d8/cas/scheduler/action_messages.rs#L275)):*
> ```XML
> }
> 
> //TODO: Make this TryFrom
> ```

super nit: period.
___
*[`cas/scheduler/action_messages.rs` line 305 at r1](https://reviewable.io/reviews/allada/turbo-cache/158#-NZxywEw-oHFZ5E0RUV7:-NZxywEw-oHFZ5E0RUV8:b-rqxvo7) ([raw file](https://github.com/allada/turbo-cache/blob/f946cd0803262d0a439138258d690090e77c03d8/cas/scheduler/action_messages.rs#L305)):*
> ```XML
> }
> 
> //TODO: Make this TryFrom
> ```

ditto.
___
*[`cas/scheduler/action_messages.rs` line 315 at r1](https://reviewable.io/reviews/allada/turbo-cache/158#-NZxz7ITDno-d8a4adHZ:-NZxz7ITDno-d8a4adH_:b-ipe42f) ([raw file](https://github.com/allada/turbo-cache/blob/f946cd0803262d0a439138258d690090e77c03d8/cas/scheduler/action_messages.rs#L315)):*
> ```XML
>             digest: Some((&val.digest).into()),
>             is_executable: val.is_executable,
>             contents: tonic::codegen::Bytes::default(),
> ```

nit: Can we import Bytes from the `bytes` package instead in the header and use it?
___
*[`cas/scheduler/action_messages.rs` line 340 at r1](https://reviewable.io/reviews/allada/turbo-cache/158#-NZxzDak7zhgiIlkAHhq:-NZxzDak7zhgiIlkAHhr:b-rqxvo7) ([raw file](https://github.com/allada/turbo-cache/blob/f946cd0803262d0a439138258d690090e77c03d8/cas/scheduler/action_messages.rs#L340)):*
> ```XML
> }
> 
> // TODO: Make this TryFrom
> ```

ditto.
___
*[`cas/scheduler/action_messages.rs` line 365 at r1](https://reviewable.io/reviews/allada/turbo-cache/158#-NZxzH3N3dSLcySts3EH:-NZxzH3N3dSLcySts3EI:b-5v3gaq) ([raw file](https://github.com/allada/turbo-cache/blob/f946cd0803262d0a439138258d690090e77c03d8/cas/scheduler/action_messages.rs#L365)):*
> ```XML
> }
> 
> // TODO: Make this TryFrom
> ```

nit: ditto.
___
*[`cas/scheduler/action_messages.rs` line 552 at r1](https://reviewable.io/reviews/allada/turbo-cache/158#-NZxzsU808h3IJj8MZZi:-NZxzsU808h3IJj8MZZj:bjn57bt) ([raw file](https://github.com/allada/turbo-cache/blob/f946cd0803262d0a439138258d690090e77c03d8/cas/scheduler/action_messages.rs#L552)):*
> ```XML
>     fn from(val: ActionStage) -> Self {
>         const RESPONSE_MESSAGE: &str = "TODO(blaise.bruer) We should put a reference something like bb_browser";
>         let logs_from = |result: &ActionResult| -> HashMap<String, LogFile> {
> ```

nit: Lets instead bring in the `HashMap` itself as a parameter (non-ref). This will remove the need for a small copy and be more precise in what we are doing/need.
___
*[`cas/scheduler/action_messages.rs` line 574 at r1](https://reviewable.io/reviews/allada/turbo-cache/158#-NZy-LwK7upnVya6Fxb2:-NZy-LwK7upnVya6Fxb3:bz2nf77) ([raw file](https://github.com/allada/turbo-cache/blob/f946cd0803262d0a439138258d690090e77c03d8/cas/scheduler/action_messages.rs#L574)):*
> ```XML
> 
>             ActionStage::Completed(action_result) => {
>                 let server_logs = logs_from(&action_result);
> ```

nit: I suggest inlining this.
___
*[`cas/scheduler/action_messages.rs` line 584 at r1](https://reviewable.io/reviews/allada/turbo-cache/158#-NZy-PRJANQxnPiBvYpo:-NZy-PRJANQxnPiBvYpp:b-5v3gaq) ([raw file](https://github.com/allada/turbo-cache/blob/f946cd0803262d0a439138258d690090e77c03d8/cas/scheduler/action_messages.rs#L584)):*
> ```XML
>             }
>             ActionStage::Error((error, action_result)) => {
>                 let server_logs = logs_from(&action_result);
> ```

nit: ditto.
___
*[`cas/scheduler/action_messages.rs` line 588 at r1](https://reviewable.io/reviews/allada/turbo-cache/158#-NZy-U8M0pbiKAnki9Av:-NZy-U8M0pbiKAnki9Aw:b-pom2kv) ([raw file](https://github.com/allada/turbo-cache/blob/f946cd0803262d0a439138258d690090e77c03d8/cas/scheduler/action_messages.rs#L588)):*
> ```XML
>                     result: Some(action_result.into()),
>                     cached_result: false,
>                     status: Some(error.into()), // map_or(Status::default(), |v| v.into())),
> ```

nit: remove comment.
___
*[`cas/scheduler/action_messages.rs` line 620 at r1](https://reviewable.io/reviews/allada/turbo-cache/158#-NZy-zu58MUf2S7EqdQi:-NZy-zu58MUf2S7EqdQj:b-iipjm8) ([raw file](https://github.com/allada/turbo-cache/blob/f946cd0803262d0a439138258d690090e77c03d8/cas/scheduler/action_messages.rs#L620)):*
> ```XML
>             output_directory_symlinks: val.output_directory_symlinks.into_iter().map(Into::into).collect(),
>             exit_code: val.exit_code,
>             stdout_raw: tonic::codegen::Bytes::default(),
> ```

nit: ditto
___
*[`cas/scheduler/action_messages.rs` line 622 at r1](https://reviewable.io/reviews/allada/turbo-cache/158#-NZy008wA5A2uwbYDglM:-NZy008wA5A2uwbYDglN:b-iipjm8) ([raw file](https://github.com/allada/turbo-cache/blob/f946cd0803262d0a439138258d690090e77c03d8/cas/scheduler/action_messages.rs#L622)):*
> ```XML
>             stdout_raw: tonic::codegen::Bytes::default(),
>             stdout_digest: Some(val.stdout_digest.into()),
>             stderr_raw: tonic::codegen::Bytes::default(),
> ```

nit: ditto

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/158)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @allada)

___
*[`cas/scheduler/action_messages.rs` line 552 at r1](https://reviewable.io/reviews/allada/turbo-cache/158#-NZxzsU808h3IJj8MZZi:-N_06Z7jEx66jIJlyac3:bz2lh7v) ([raw file](https://github.com/allada/turbo-cache/blob/f946cd0803262d0a439138258d690090e77c03d8/cas/scheduler/action_messages.rs#L552)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Lets instead bring in the `HashMap` itself as a parameter (non-ref). This will remove the need for a small copy and be more precise in what we are doing/need.
</blockquote></details>

Hmm I'm not sure how to make this non-ref. If I move it into the closure I'd have to `clone` it in the struct below.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/158)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @aaronmondal)

___
*[`cas/scheduler/action_messages.rs` line 552 at r1](https://reviewable.io/reviews/allada/turbo-cache/158#-NZxzsU808h3IJj8MZZi:-N_0EXYJ0pb71UJsQpdX:b-aagp7e) ([raw file](https://github.com/allada/turbo-cache/blob/f946cd0803262d0a439138258d690090e77c03d8/cas/scheduler/action_messages.rs#L552)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Hmm I'm not sure how to make this non-ref. If I move it into the closure I'd have to `clone` it in the struct below.
</blockquote></details>

Yeah, that's the point. The idea is to always allow the caller to choose if they can move or clone if it needs to clone it internally. This allows the caller to choose if a clone is needed rather than blindly cloning.

I don't really mind in this case, since it's a private function and it is always going to clone in any case, but it's a good habit to get into since it can reduce a lot of needless clones simply by allowing the caller to choose if a clone is needed.
___
*[`cas/scheduler/action_messages.rs` line 552 at r1](https://reviewable.io/reviews/allada/turbo-cache/158#-N_0FSXc5pf6tLqHA2Y6:-N_0FSXc5pf6tLqHA2Y7:b-60eivn) ([raw file](https://github.com/allada/turbo-cache/blob/f946cd0803262d0a439138258d690090e77c03d8/cas/scheduler/action_messages.rs#L552)):*
> ```XML
>     fn from(val: ActionStage) -> Self {
>         const RESPONSE_MESSAGE: &str = "TODO(blaise.bruer) We should put a reference something like bb_browser";
>         let logs_from = |result: &ActionResult| -> HashMap<String, LogFile> {
> ```

nit: Can we make this a normal `fn`, it doesn't look like we capture anything.

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/158)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @allada)

___
*[`cas/scheduler/action_messages.rs` line 552 at r1](https://reviewable.io/reviews/allada/turbo-cache/158#-NZxzsU808h3IJj8MZZi:-N_0U-aQEVVI8Idp5s4d:b-15n6ua) ([raw file](https://github.com/allada/turbo-cache/blob/f946cd0803262d0a439138258d690090e77c03d8/cas/scheduler/action_messages.rs#L552)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Yeah, that's the point. The idea is to always allow the caller to choose if they can move or clone if it needs to clone it internally. This allows the caller to choose if a clone is needed rather than blindly cloning.

I don't really mind in this case, since it's a private function and it is always going to clone in any case, but it's a good habit to get into since it can reduce a lot of needless clones simply by allowing the caller to choose if a clone is needed.
</blockquote></details>

Ah I think now I get it. Right, the other code was cloning anyways, but less expliticly :sweat_smile:

**Review by allada — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/158)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronmondal)

**Pull request merged**
