### PR TITLE
Use recent Ubuntu with Clang as build environment

### PR DESCRIPTION
**Pull request by aaronmondal**
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/144)

### CODE REVIEW

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/144)* status: all files reviewed, 1 unresolved discussion (waiting on @aaronmondal)

___
*[`.github/workflows/main.yml` line 28 at r1](https://reviewable.io/reviews/allada/turbo-cache/144#-NZnDl7B9Gtx83zijoM1:-NZnDl7B9Gtx83zijoM2:b-vykbo1) ([raw file](https://github.com/allada/turbo-cache/blob/93607006cce4978ec9b029f753bc0fc06e4137fa/.github/workflows/main.yml#L28)):*
> ```YAML
> 
>     - name: Bazel test
>       run: bazel test --config=generic_clang //...
> ```

Is this required now? I'd rather do this as a separate test if you want to test this config.

Also, I thought there was a ubuntu `clang` package replaces `gcc`?

**Comment by aaronmondal** [comment]
*[`.github/workflows/main.yml` line 28 at r1](https://reviewable.io/reviews/allada/turbo-cache/144#-NZnDl7B9Gtx83zijoM1:-NZnFrLPEJuEbWfS1DvU:b-3yczln) ([raw file](https://github.com/allada/turbo-cache/blob/93607006cce4978ec9b029f753bc0fc06e4137fa/.github/workflows/main.yml#L28)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Is this required now? I'd rather do this as a separate test if you want to test this config.

Also, I thought there was a ubuntu `clang` package replaces `gcc`?
</blockquote></details>

The ubuntu clang package is what is used in the Dockerfile. But that doesn't set the CC environment variable which is required by Bazel's C++ toolchain autodetection. So instead this variable is conditionally set by the `generic_clang` config in `.bazelrc`. This way Clang isn't a hard requirement when building locally (if the CC override was always set we'd require every user to locally install clang).

I agree that it would be nicer to test both Clang and GCC as GCC builds would be untested after this change. We're only using it to build protoc, but it's probably still a good idea to test both.

Maybe I could split the unit-test workflow into `unit-tests-clang` and `unit-tests-gcc`?

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/144)* status: all files reviewed, 1 unresolved discussion (waiting on @aaronmondal)

___
*[`.github/workflows/main.yml` line 28 at r1](https://reviewable.io/reviews/allada/turbo-cache/144#-NZnDl7B9Gtx83zijoM1:-NZnJ7tV0oEkJhr4vOsL:b-xl0zx7) ([raw file](https://github.com/allada/turbo-cache/blob/93607006cce4978ec9b029f753bc0fc06e4137fa/.github/workflows/main.yml#L28)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

The ubuntu clang package is what is used in the Dockerfile. But that doesn't set the CC environment variable which is required by Bazel's C++ toolchain autodetection. So instead this variable is conditionally set by the `generic_clang` config in `.bazelrc`. This way Clang isn't a hard requirement when building locally (if the CC override was always set we'd require every user to locally install clang).

I agree that it would be nicer to test both Clang and GCC as GCC builds would be untested after this change. We're only using it to build protoc, but it's probably still a good idea to test both.

Maybe I could split the unit-test workflow into `unit-tests-clang` and `unit-tests-gcc`?
</blockquote></details>

I'm more worried that we are not testing defaults. At least, can we use bazel's auto-detection and just globally set `CC` to clang in the Dockerfile, so users don't see this magic config and have to go digging to figure out what it does?

**Comment by aaronmondal** [comment]
@allada WDYT about something like this:

```yaml
# main.yaml

matrix:
  compiler: [gcc, clang]

unit-test:
  ...
  env:
    CC: ${{ matrix.compiler }}
```

**Comment by aaronmondal** [comment]
*[`.github/workflows/main.yml` line 28 at r1](https://reviewable.io/reviews/allada/turbo-cache/144#-NZnDl7B9Gtx83zijoM1:-NZnOgdk8lv1ZfV6_kLZ:bkgvi00) ([raw file](https://github.com/allada/turbo-cache/blob/93607006cce4978ec9b029f753bc0fc06e4137fa/.github/workflows/main.yml#L28)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I'm more worried that we are not testing defaults. At least, can we use bazel's auto-detection and just globally set `CC` to clang in the Dockerfile, so users don't see this magic config and have to go digging to figure out what it does?
</blockquote></details>

I've removed the `generic_clang` config and set it directly in the Dockerfile. This way we're testing just a default build configuration now and `bazel build ...` and `bazel test ...` should keep working as before with autodetection handled by the user's local toolchain config.

**Review by allada — APPROVED** [review]
Yeah that looks good :smile: 

:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/144#-:-NZnRT3-EgbuE9ct_ulC:bqv2lwm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronmondal)

**Pull request merged**
