### PR TITLE
Fix flakey tests

### PR DESCRIPTION
**Pull request by allada**
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/265)

### CODE REVIEW

**Review by MarcusSorealheis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/265#-:-Ndx-D2p7EJizsECe1x8:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved

**Review by allada — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/265)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Comment by chrisstaite-menlo** [comment]
This doesn't appear to fix it...
```
Text file busy (os error 26) : Could not execute precondition command \"/root/.cache/bazel/_bazel_root/fb30063f7ca6481d2ab027994f595558/sandbox/processwrapper-sandbox/109/execroot/turbo-cache/_tmp/83df288b6bf672a9ac1862ea4202dc78/15849863113607457512/scripts/precondition.sh
```
Got this on unit-tests on `main`

**Review by allada — COMMENTED** [review]
Yeah trying to figure out what is causing it. I'm not 100% sure yet.

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/265#-:-Ne3fxyY0y1ts_zXNDh4:b-63zdjm)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
