### PR TITLE
Scheduler is now an interface/trait

### LINKED ISSUE #140: Migrate scheduler to an interface to support multiple implementations
Similar to how stores work, we should migrate schedulers to a trait/interface so we can develop multiple implementations of it.

### PR DESCRIPTION
**Pull request by allada**
Final PR in the series to migrate the scheduler to a trait.

This will allow more complex functionality and special configs
for when the scheduler should do additional steps or interact
with workers in a unique way.

closes #140

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/150)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@chrisstaite-menlo I'm not sure if you know how to review just one commit of this PR, but this PR depends on #149

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/150#-:-NZsJeBMA_Ll0d3gWvMv:b22q46a)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)

**Review by chrisstaite-menlo — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 5 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/150)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @allada)

___
*[`cas/scheduler/scheduler.rs` line 28 at r2](https://reviewable.io/reviews/allada/turbo-cache/150#-NZtSJJ4719LcPw0uwl7:-NZtSJJ4719LcPw0uwl8:bexmnhd) ([raw file](https://github.com/allada/turbo-cache/blob/0aa0654f08acbb43c0abcd048fe149604dbeb1dd/cas/scheduler/scheduler.rs#L28)):*
> ```XML
> /// actions and workers.
> #[async_trait]
> pub trait Scheduler: Sync + Send + Unpin {
> ```

This trait should only contain `add_action` all of the other functions are implementation details for the `SimpleScheduler`.
___
*[`cas/scheduler/scheduler.rs` line 47 at r2](https://reviewable.io/reviews/allada/turbo-cache/150#-NZtSYJP2rRYm_e9ADd2:-NZtSYJP2rRYm_e9ADd3:bwml5dm) ([raw file](https://github.com/allada/turbo-cache/blob/0aa0654f08acbb43c0abcd048fe149604dbeb1dd/cas/scheduler/scheduler.rs#L47)):*
> ```XML
>     );
> 
>     /// Adds an action to the scheduler for remote execution.
> ```

This comment is incorrect and it's been driving me kinda mad :)

**Review by chrisstaite-menlo — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/150)* status: all files reviewed, 1 unresolved discussion (waiting on @allada)

___
*[`cas/scheduler/scheduler.rs` line 30 at r3](https://reviewable.io/reviews/allada/turbo-cache/150#-N_-nwVe-Gl9m97ErhCT:-N_-nwVe-Gl9m97ErhCU:bbjzlix) ([raw file](https://github.com/allada/turbo-cache/blob/f086c20f3ac86d6583d75c356f1a9e51a11d6e10/cas/scheduler/scheduler.rs#L30)):*
> ```XML
> pub trait ActionScheduler: Sync + Send + Unpin {
>     /// Returns the platform property manager.
>     fn get_platform_property_manager(&self) -> &PlatformPropertyManager;
> ```

Pretty sure this isn't required for the `ActionScheduler` either?

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/150)* status: all files reviewed, 1 unresolved discussion (waiting on @allada)

___
*[`cas/scheduler/scheduler.rs` line 28 at r2](https://reviewable.io/reviews/allada/turbo-cache/150#-NZtSJJ4719LcPw0uwl7:-NZtTbJsEQ8tyRI6G3uE:bnzrx3j) ([raw file](https://github.com/allada/turbo-cache/blob/0aa0654f08acbb43c0abcd048fe149604dbeb1dd/cas/scheduler/scheduler.rs#L28)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

This trait should only contain `add_action` all of the other functions are implementation details for the `SimpleScheduler`.
</blockquote></details>

I thought a lot about this and was struggling to decide if the scheduler<->worker interaction also needed to be abstracted.

I kept using the example of `LambdaScheduler` that used AWS lambdas as a base case. Since workers don't really exist in the traditional sense. With this example only `ActionScheduler` has any meaning in this regard and `WorkerScheduler` is non-existent. Then I started thinking, what about a use case where a user might have another source-of-truth for actions (like a proprietary action queue) and in this case the user only wants `WorkerScheduler` and they could/would implement their logic on how to get actions in this custom scheduler.

In any sense, I think it makes sense to split it into two traits.
___
*[`cas/scheduler/scheduler.rs` line 47 at r2](https://reviewable.io/reviews/allada/turbo-cache/150#-NZtSYJP2rRYm_e9ADd2:-N_-R_dT3rtpjmO22xWW:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/0aa0654f08acbb43c0abcd048fe149604dbeb1dd/cas/scheduler/scheduler.rs#L47)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

This comment is incorrect and it's been driving me kinda mad :)
</blockquote></details>

Done.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/150)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisstaite-menlo)

___
*[`cas/scheduler/scheduler.rs` line 30 at r3](https://reviewable.io/reviews/allada/turbo-cache/150#-N_-nwVe-Gl9m97ErhCT:-N_-pXJs0Uwkd-pGsZq7:b-p8ofdm) ([raw file](https://github.com/allada/turbo-cache/blob/f086c20f3ac86d6583d75c356f1a9e51a11d6e10/cas/scheduler/scheduler.rs#L30)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Pretty sure this isn't required for the `ActionScheduler` either?
</blockquote></details>

Sadly both `ActionScheduler` and `WorkerScheduler` need it.
ActionScheduler:
* CapabilitiesServer needs to get all properties to tell clients about supported properties.
* ExecutionServer needs to translate the config `Minimum`, `Exact`, `Priority` into the union version `Minimum(u64)`, `Priority(String)`, `Priority(String)` versions.

WorkerScheduler:
* WorkerApiServer needs to also translate the config->union, to inform the scheduler of the properties the instance supports.

**Comment by chrisstaite-menlo** [comment]
*[`cas/scheduler/scheduler.rs` line 30 at r3](https://reviewable.io/reviews/allada/turbo-cache/150#-N_-nwVe-Gl9m97ErhCT:-N_06V2w-CPtSI8wOUGn:bqul0n4) ([raw file](https://github.com/allada/turbo-cache/blob/f086c20f3ac86d6583d75c356f1a9e51a11d6e10/cas/scheduler/scheduler.rs#L30)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Sadly both `ActionScheduler` and `WorkerScheduler` need it.
ActionScheduler:
* CapabilitiesServer needs to get all properties to tell clients about supported properties.
* ExecutionServer needs to translate the config `Minimum`, `Exact`, `Priority` into the union version `Minimum(u64)`, `Priority(String)`, `Priority(String)` versions.

WorkerScheduler:
* WorkerApiServer needs to also translate the config->union, to inform the scheduler of the properties the instance supports.
</blockquote></details>

My main issue is how do I proxy that through with a `GrpcScheduler`.  See https://github.com/chrisstaite-menlo/turbo-cache/commit/de97fb4895b6e0e67b38965b873bfa1c3e549bf8

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/150)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

___
*[`cas/scheduler/scheduler.rs` line 30 at r3](https://reviewable.io/reviews/allada/turbo-cache/150#-N_-nwVe-Gl9m97ErhCT:-N_0DerL8gQ_S3_883qO:bh7cl2y) ([raw file](https://github.com/allada/turbo-cache/blob/f086c20f3ac86d6583d75c356f1a9e51a11d6e10/cas/scheduler/scheduler.rs#L30)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

I figured it out, I just grab it from the capabilities request.
</blockquote></details>

Yeah, I thought about this, since the properties do not change, you can just grab all properties through the GRPC request and rebuild the `PlatformPropertiesManager`, since the structure is quite simple (just as hash map).

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 2 of 10 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/150)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)

**Pull request merged**
