### PR TITLE
Fix incorrect type check.

### PR DESCRIPTION
**Pull request by chrisstaite-menlo**
When re-factoring the GrpcScheduler change, a dodgy copy-paste made it in.  Fix up the type check to the correct type.

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/203)

### CODE REVIEW

**Comment by chrisstaite-menlo** [comment]
Yes, and it turns out there's a bug in `action_name` too...

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/203)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/scheduler/action_messages.rs` line 780 at r2](https://reviewable.io/reviews/allada/turbo-cache/203#-N_dhHCC96vhdnUxt3cs:-N_dhHCC96vhdnUxt3ct:bdr2knc) ([raw file](https://github.com/allada/turbo-cache/blob/2b6eb14bb86ba45fa381208beb0a22fa6d23c394/cas/scheduler/action_messages.rs#L780)):*
> ```XML
> }
> 
> fn from_any<T>(message: &Any) -> Result<T, Error>
> ```

clever! :100: 
___
*[`cas/scheduler/action_messages.rs` line 840 at r2](https://reviewable.io/reviews/allada/turbo-cache/203#-N_dhVneA27fr2OQj5J1:-N_dhVneA27fr2OQj5J2:b-cbafrf) ([raw file](https://github.com/allada/turbo-cache/blob/2b6eb14bb86ba45fa381208beb0a22fa6d23c394/cas/scheduler/action_messages.rs#L840)):*
> ```XML
>         };
> 
>         println!("Operation name: {}", operation.name);
> ```

nit: debug artifact.
___
*[`cas/scheduler/action_messages.rs` line 899 at r2](https://reviewable.io/reviews/allada/turbo-cache/203#-N_diJu6Cwe-aQjpdXbg:-N_diJu730q3R_dJ0Jf4:b-7zzhy9) ([raw file](https://github.com/allada/turbo-cache/blob/2b6eb14bb86ba45fa381208beb0a22fa6d23c394/cas/scheduler/action_messages.rs#L899)):*
> ```XML
>         Self {
>             name: val.unique_qualifier.action_name(),
>             metadata: Some(to_any(&metadata)),
> ```

nit: Here (and above) Don't we need to deal with the result of `to_any()`? I'm kinda confused on how this is compiling.

**Review by allada — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/203)* status: all files reviewed, 3 unresolved discussions (waiting on @chrisstaite-menlo)

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/203)* status: all files reviewed, 3 unresolved discussions (waiting on @chrisstaite-menlo)

**Pull request merged**
