### PR TITLE
Fix clippy warnings for scheduler directory

### PR DESCRIPTION
**Pull request by aaronmondal**
Final clippy patch. After this we can enable clippy by default.

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/181)

### CODE REVIEW

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/181)* status: all files reviewed, 1 unresolved discussion (waiting on @aaronmondal)

___
*[`cas/scheduler/simple_scheduler.rs` line 452 at r1](https://reviewable.io/reviews/allada/turbo-cache/181#-N_LCx6f86qpgahtCtJl:-N_LCx6f86qpgahtCtJm:bpu1stt) ([raw file](https://github.com/allada/turbo-cache/blob/65c4232672e7db42d67439680a00d7b2c110e800/cas/scheduler/simple_scheduler.rs#L452)):*
> ```XML
>         }
> 
>         let did_complete = matches!(action_stage, ActionStage::Completed(_));
> ```

lets not change this, I have another PR fixing this #179

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/181)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @allada)

___
*[`cas/scheduler/simple_scheduler.rs` line 452 at r1](https://reviewable.io/reviews/allada/turbo-cache/181#-N_LCx6f86qpgahtCtJl:-N_LKbxp0HWTI3JrA8OF:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/65c4232672e7db42d67439680a00d7b2c110e800/cas/scheduler/simple_scheduler.rs#L452)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

lets not change this, I have another PR fixing this #179
</blockquote></details>

Done.

**Review by allada — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/181)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronmondal)

**Review by allada — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/181#-:-N_LTrP69LUCosL9d4Vc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronmondal)

**Review by allada — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/181)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronmondal)

**Pull request merged**
