### PR TITLE
Fix a couple of nits with the timestamp additions.

### PR DESCRIPTION
**Pull request by chrisstaite-menlo**
Some nits that weren't in #113 because it auto-merged.

- - -
This change is [Reviewable](https://reviewable.io/reviews/allada/turbo-cache/119)

### CODE REVIEW

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/119#-:-NZ70Ruw2z7xDDVB7ILY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/119)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisstaite-menlo)

*[a discussion](https://reviewable.io/reviews/allada/turbo-cache/119#-NZ70UAQ8HvbPvMg53kd:-NZ70UAQ8HvbPvMg53ke:boosdfj) (no related file):*
If you want from now on, I can let you click the merge button when you are ready?

___

**Review by allada — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/119)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisstaite-menlo)

**Comment by chrisstaite-menlo** [comment]
It's ready to merge, but there doesn't appear to be a button to merge it.

**Pull request merged**
